/*

Filename: horizon_map.c 

Map Include File

 Info:
   Section       :
   Bank          : 0
   Map size      : 32 x 4
   Tile offset   : 0

This file was generated by: Gimp/Console png2gbtiles
*/

#define horizon_map_width 32
#define horizon_map_height 4
#define horizon_map_tiles 128
#define horizon_map_bytes 128

extern unsigned char horizon_map[];
extern unsigned char horizon_map_attr[];

