/*

Filename: horizon_map.c 

Map Include File

 Info:
   Section       :
   Bank          : 0
   Map size      : 32 x 3
   Tile offset   : 0

This file was generated by: Gimp/Console png2gbtiles
*/

#define horizon_map_width 32
#define horizon_map_height 3
#define horizon_map_tiles 96
#define horizon_map_bytes 96

extern unsigned char horizon_map[];
extern unsigned char horizon_map_attr[];

