/*

Filename: nes_map.c 

Map Include File

 Info:
   Section       :
   Bank          : 0
   Map size      : 32 x 160
   Tile offset   : 0

This file was generated by: Gimp/Console png2gbtiles
*/

#define nes_map_width 32
#define nes_map_height 160
#define nes_map_tiles 5120
#define nes_map_bytes 5120

extern unsigned char nes_map[];
extern unsigned char nes_map_attr[];

