/*

Filename: nes_map.c 

Map Include File

 Info:
   Section       :
   Bank          : 0
   Map size      : 32 x 128
   Tile offset   : 0

This file was generated by: Gimp/Console png2gbtiles
*/

#define nes_map_width 32
#define nes_map_height 128
#define nes_map_tiles 4096
#define nes_map_bytes 4096

extern unsigned char nes_map[];
extern unsigned char nes_map_attr[];

