//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_nesaxelay_background_map_H
#define METASPRITE_nesaxelay_background_map_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define nesaxelay_background_map_TILE_ORIGIN 0
#define nesaxelay_background_map_TILE_W 8
#define nesaxelay_background_map_TILE_H 8
#define nesaxelay_background_map_WIDTH 256
#define nesaxelay_background_map_HEIGHT 1024
#define nesaxelay_background_map_TILE_COUNT 178
#define nesaxelay_background_map_PALETTE_COUNT 8
#define nesaxelay_background_map_COLORS_PER_PALETTE 4
#define nesaxelay_background_map_TOTAL_COLORS 32
#define nesaxelay_background_map_MAP_ATTRIBUTES nesaxelay_background_map_map_attributes
#define nesaxelay_background_map_MAP_ATTRIBUTES_WIDTH 32
#define nesaxelay_background_map_MAP_ATTRIBUTES_HEIGHT 128
#define nesaxelay_background_map_MAP_ATTRIBUTES_PACKED_WIDTH 32
#define nesaxelay_background_map_MAP_ATTRIBUTES_PACKED_HEIGHT 128

BANKREF_EXTERN(nesaxelay_background_map)

extern const palette_color_t nesaxelay_background_map_palettes[32];
extern const uint8_t nesaxelay_background_map_tiles[2848];

extern const unsigned char nesaxelay_background_map_map[4096];
extern const unsigned char nesaxelay_background_map_map_attributes[4096];

#endif
