//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_sprite_boulders_H
#define METASPRITE_sprite_boulders_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define sprite_boulders_TILE_H 16
#define sprite_boulders_WIDTH 16
#define sprite_boulders_HEIGHT 16
#define sprite_boulders_TILE_COUNT 34
#define sprite_boulders_PIVOT_X 0
#define sprite_boulders_PIVOT_Y 0
#define sprite_boulders_PIVOT_W 16
#define sprite_boulders_PIVOT_H 16

BANKREF_EXTERN(sprite_boulders)

extern const palette_color_t sprite_boulders_palettes[32];
extern const uint8_t sprite_boulders_tiles[544];

extern const metasprite_t* const sprite_boulders_metasprites[9];

#endif