//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_sprite_shots_H
#define METASPRITE_sprite_shots_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define sprite_shots_TILE_ORIGIN 0
#define sprite_shots_TILE_W 8
#define sprite_shots_TILE_H 16
#define sprite_shots_WIDTH 8
#define sprite_shots_HEIGHT 16
#define sprite_shots_TILE_COUNT 18
#define sprite_shots_PALETTE_COUNT 8
#define sprite_shots_COLORS_PER_PALETTE 4
#define sprite_shots_TOTAL_COLORS 32
#define sprite_shots_PIVOT_X 0
#define sprite_shots_PIVOT_Y 0
#define sprite_shots_PIVOT_W 8
#define sprite_shots_PIVOT_H 16

BANKREF_EXTERN(sprite_shots)

extern const palette_color_t sprite_shots_palettes[32];
extern const uint8_t sprite_shots_tiles[288];

extern const metasprite_t* const sprite_shots_metasprites[9];

#endif
