//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_sprite_ship_canopy_H
#define METASPRITE_sprite_ship_canopy_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define sprite_ship_canopy_TILE_H 16
#define sprite_ship_canopy_WIDTH 8
#define sprite_ship_canopy_HEIGHT 16
#define sprite_ship_canopy_TILE_COUNT 4
#define sprite_ship_canopy_PIVOT_X 0
#define sprite_ship_canopy_PIVOT_Y 0
#define sprite_ship_canopy_PIVOT_W 8
#define sprite_ship_canopy_PIVOT_H 16

BANKREF_EXTERN(sprite_ship_canopy)

extern const palette_color_t sprite_ship_canopy_palettes[32];
extern const uint8_t sprite_ship_canopy_tiles[64];

extern const metasprite_t* const sprite_ship_canopy_metasprites[5];

#endif